const test=require('node:test'),assert=require('node:assert/strict'),R=require('../roster.js'),XLSX=require('../vendor/xlsx.full.min.js');
const columns=R.headers;
const data=['Ms Chen','1A1','Li Ming','001234567890123456','2027-01-12','09:00'];
function book(rows=[data]){return XLSX.utils.book_new(XLSX.utils.aoa_to_sheet([columns,...rows]),'Roster');}
function parse(wb){return R.parseSheet(wb,'Roster',XLSX);}
test('six-column roster preserves text IDs and normalizes dates/times',()=>{const result=parse(book());assert.deepEqual(result.issues,[]);assert.equal(result.rows[0].studentId,data[3]);assert.equal(result.rows[0].examTime,'09:00');});
test('Excel workbook bytes round-trip and reordered headers work',()=>{const b=book(),copy=XLSX.read(XLSX.write(b,{type:'buffer',bookType:'xlsx'}),{type:'buffer',raw:true,cellNF:true});assert.equal(parse(copy).rows[0].studentId,data[3]);const reordered=XLSX.utils.book_new(XLSX.utils.aoa_to_sheet([[...columns].reverse(),[...data].reverse()]),'Roster');assert.equal(parse(reordered).rows[0].teacher,'Ms Chen');});
test('native Excel dates, times, and leading-zero numeric formatting',()=>{const b=book(),s=b.Sheets.Roster;s.D2={t:'n',v:123,z:'000000'};s.E2={t:'n',v:46401,z:'yyyy-mm-dd'};s.F2={t:'n',v:9.5/24,z:'hh:mm'};const r=parse(b);assert.deepEqual(r.issues,[]);assert.equal(r.rows[0].studentId,'000123');assert.equal(r.rows[0].examDate,'2027-01-14');assert.equal(r.rows[0].examTime,'09:30');});
test('1904 Excel epoch is recognized',()=>{const b=book();b.Workbook={WBProps:{date1904:true}};b.Sheets.Roster.E2={t:'n',v:44939,z:'yyyy-mm-dd'};assert.equal(parse(b).rows[0].examDate,'2027-01-14');});
test('CSV keeps numeric-looking IDs as strings',()=>{const csv=[columns,data].map(r=>r.join(',')).join('\r\n'),b=XLSX.read(csv,{type:'string',raw:true});assert.equal(R.parseSheet(b,b.SheetNames[0],XLSX).rows[0].studentId,data[3]);});
test('missing fields, duplicate IDs and same-teacher slot collisions reject entire upload',()=>{for(const rows of [[data,[...data.slice(0,2),'','different','2027-01-12','10:00']],[data,[data[0],'1A2','Other',data[3],data[4],'10:00']],[data,[data[0],'1A2','Other','X',data[4],data[5]]]]){const r=parse(book(rows));assert.ok(r.issues.length);assert.deepEqual(r.rows,[]);}assert.equal(parse(book([data,['Mr Wu','1A2','Other','X',data[4],data[5]]])).rows.length,2);});
test('invalid dates and times and formulas are rejected',()=>{assert.throws(()=>R.dateText('2027-02-29'));assert.throws(()=>R.dateText('01/02/2027'));assert.throws(()=>R.timeText('25:00'));assert.equal(R.timeText('9:15 PM'),'21:15');const b=book();b.Sheets.Roster.D2.f='1+1';assert.match(parse(b).issues[0],/formula/);});
test('unsafe numeric IDs and duplicate/missing headers are rejected',()=>{const b=book();b.Sheets.Roster.D2={t:'n',v:1234567890123456};assert.match(parse(b).issues[0],/rounded/);const missing=book();missing.Sheets.Roster.A1.v='Other';assert.throws(()=>parse(missing),/Missing headers/);});
test('explicit mapping accepts arbitrary reordered headers and ignores extra columns',()=>{const b=XLSX.utils.book_new(XLSX.utils.aoa_to_sheet([['Name','Unused','When','Who','Group','Number','Day'],[data[2],'ignored',data[5],data[0],data[1],data[3],data[4]]]),'Roster');const mapping={teacher:3,className:4,studentName:0,studentId:5,examDate:6,examTime:2};const result=R.parseSheet(b,'Roster',XLSX,mapping);assert.deepEqual(result.issues,[]);R.keys.forEach((key,i)=>assert.equal(result.rows[0][key],data[i]));});
test('mapping rejects missing, duplicate and out-of-range source columns',()=>{const mapping=Object.fromEntries(R.keys.map((k,i)=>[k,i]));for(const value of [null,undefined,-1,6,1.5,0])assert.throws(()=>R.parseSheet(book(),'Roster',XLSX,{...mapping,examTime:value}),/Choose/);});
test('mapping suggestions are conservative and duplicate labels remain selectable by column',()=>{const b=book();b.Sheets.Roster.C1.v='Student Name';b.Sheets.Roster.E1.v='Date';b.Sheets.Roster.F1.v='Time';const columns=R.sheetColumns(b,'Roster',XLSX);assert.deepEqual(R.suggestMapping(columns),Object.fromEntries(R.keys.map((k,i)=>[k,i])));b.Sheets.Roster.D1.v='Student Name';const duplicate=R.sheetColumns(b,'Roster',XLSX);assert.equal(R.suggestMapping(duplicate).studentName,undefined);assert.equal(R.parseSheet(b,'Roster',XLSX,Object.fromEntries(R.keys.map((k,i)=>[k,i]))).rows[0].studentId,data[3]);});
test('mapped fields preserve Excel numeric date/time and ID handling and reject formulas',()=>{const b=book(),mapping=Object.fromEntries(R.keys.map((k,i)=>[k,i]));b.Sheets.Roster.D2={t:'n',v:123,z:'000000'};b.Sheets.Roster.E2={t:'n',v:46401};b.Sheets.Roster.F2={t:'n',v:9.5/24};const result=R.parseSheet(b,'Roster',XLSX,mapping);assert.equal(result.rows[0].studentId,'000123');assert.equal(result.rows[0].examDate,'2027-01-14');assert.equal(result.rows[0].examTime,'09:30');b.Sheets.Roster.D2.f='123';assert.match(R.parseSheet(b,'Roster',XLSX,mapping).issues[0],/formula/);});
test('readable timetable dates normalize while ambiguous or inconsistent dates fail',()=>{for(const input of ['Thursday, June 25, 2026','25 June 2026','Jun 25, 2026','25/06/2026','06/25/2026'])assert.equal(R.dateText(input),'2026-06-25');for(const input of ['Friday, June 25, 2026','June 31, 2026','03/04/2026','June 25'])assert.throws(()=>R.dateText(input));const b=book();b.Sheets.Roster.E2={t:'s',v:'Thursday, June 25, 2026'};const result=parse(b);assert.equal(result.rows[0].examDate,'2026-06-25');assert.match(result.notices[0],/2026-06-25/);});
