const test=require('node:test'),assert=require('node:assert/strict'),R=require('../roster.js'),XLSX=require('../vendor/xlsx.full.min.js');
const columns=R.headers;
const data=['Ms Chen','1A1','Li Ming','001234567890123456','2027-01-12','09:00'];
function book(rows=[data]){return XLSX.utils.book_new(XLSX.utils.aoa_to_sheet([columns,...rows]),'Roster');}
function parse(wb){return R.parseSheet(wb,'Roster',XLSX);}
test('six-column roster preserves text IDs and normalizes dates/times',()=>{const result=parse(book());assert.deepEqual(result.issues,[]);assert.equal(result.rows[0].studentId,data[3]);assert.equal(result.rows[0].examTime,'09:00');});
test('Excel workbook bytes round-trip and reordered headers work',()=>{const b=book(),copy=XLSX.read(XLSX.write(b,{type:'buffer',bookType:'xlsx'}),{type:'buffer',raw:true,cellNF:true});assert.equal(parse(copy).rows[0].studentId,data[3]);const reordered=XLSX.utils.book_new(XLSX.utils.aoa_to_sheet([[...columns].reverse(),[...data].reverse()]),'Roster');assert.equal(parse(reordered).rows[0].teacher,'Ms Chen');});
test('native Excel dates, times, and leading-zero numeric formatting',()=>{const b=book(),s=b.Sheets.Roster;s.D2={t:'n',v:123,z:'000000'};s.E2={t:'n',v:46401,z:'yyyy-mm-dd'};s.F2={t:'n',v:9.5/24,z:'hh:mm'};const r=parse(b);assert.deepEqual(r.issues,[]);assert.equal(r.rows[0].studentId,'000123');assert.equal(r.rows[0].examDate,'2027-01-14');assert.equal(r.rows[0].examTime,'09:30');});
test('1904 Excel epoch is recognized',()=>{const b=book();b.Workbook={WBProps:{date1904:true}};b.Sheets.Roster.E2={t:'n',v:44939,z:'yyyy-mm-dd'};assert.equal(parse(b).rows[0].examDate,'2027-01-14');});
test('CSV keeps numeric-looking IDs as strings',()=>{const csv=[columns,data].map(r=>r.join(',')).join('\r\n'),b=XLSX.read(csv,{type:'string',raw:true});assert.equal(R.parseSheet(b,b.SheetNames[0],XLSX).rows[0].studentId,data[3]);});
test('missing fields, duplicate IDs and same-teacher slot collisions reject entire upload',()=>{for(const rows of [[data,[...data.slice(0,2),'','different','2027-01-12','10:00']],[data,[data[0],'1A2','Other',data[3],data[4],'10:00']],[data,[data[0],'1A2','Other','X',data[4],data[5]]]]){const r=parse(book(rows));assert.ok(r.issues.length);assert.deepEqual(r.rows,[]);}assert.equal(parse(book([data,['Mr Wu','1A2','Other','X',data[4],data[5]]])).rows.length,2);});
test('invalid dates and times and formulas are rejected',()=>{assert.throws(()=>R.dateText('2027-02-29'));assert.throws(()=>R.dateText('01/02/2027'));assert.throws(()=>R.timeText('25:00'));assert.equal(R.timeText('9:15 PM'),'21:15');const b=book();b.Sheets.Roster.D2.f='1+1';assert.match(parse(b).issues[0],/formula/);});
test('unsafe numeric IDs and duplicate/missing headers are rejected',()=>{const b=book();b.Sheets.Roster.D2={t:'n',v:1234567890123456};assert.match(parse(b).issues[0],/rounded/);const missing=book();missing.Sheets.Roster.A1.v='Other';assert.throws(()=>parse(missing),/Missing headers/);});
