const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createExamServer}=require('../server.cjs');
const secret='test-manager-secret-only-not-for-deployment';
const rows=[{teacher:'Ms Chen',className:'1A1',studentName:'Li Ming',studentId:'001',examDate:'2027-01-12',examTime:'09:00'},{teacher:'Mr Wu',className:'1A2',studentName:'Wang Fang',studentId:'002',examDate:'2027-01-12',examTime:'09:00'}];
async function fixture(t){const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'exam-server-test-')),server=createExamServer({dataDir,managerCode:secret});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(resolve=>server.close(resolve));fs.rmSync(dataDir,{recursive:true,force:true});});async function req(route,method='GET',payload,cookie='',extra={}){const r=await fetch(origin+route,{method,headers:{Origin:origin,'Content-Type':'application/json','X-Exam-Request':'1',Cookie:cookie,...extra},body:payload===undefined?undefined:JSON.stringify(payload)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''};}const manager=await req('/api/login','POST',{role:'manager',code:secret});assert.equal(manager.status,200);return {req,manager:manager.cookie,dataDir,server};}
test('private roster requires authentication and data files cannot be fetched',async t=>{const {req}=await fixture(t);assert.equal((await req('/api/roster')).status,401);assert.equal((await req('/.data/roster-private.json')).status,404);assert.equal((await req('/server.cjs')).status,404);assert.equal((await req('/api/login','POST',{role:'manager',code:'wrong'})).status,401);assert.equal((await req('/api/login','POST',{role:'manager',code:secret},'',{Origin:'https://other.example'})).status,403);});
test('one upload serves multiple teachers, each restricted to their assigned rows',async t=>{const {req,manager}=await fixture(t);assert.equal((await req('/api/roster','PUT',{expectedRevision:0,session:'2026–27 S1',rows},manager)).status,200);for(const row of rows){const code=await req('/api/teacher-code','POST',{teacher:row.teacher},manager);const teacher=await req('/api/login','POST',{role:'teacher',code:code.data.code});assert.equal(teacher.status,200);assert.deepEqual((await req('/api/roster','GET',undefined,teacher.cookie)).data.rows,[row]);assert.equal((await req('/api/roster','PUT',{expectedRevision:1,session:'hack',rows},teacher.cookie)).status,403);assert.equal((await req('/api/teachers','GET',undefined,teacher.cookie)).status,403);}});
test('bad uploads and stale manager writes leave the roster unchanged',async t=>{const {req,manager}=await fixture(t);await req('/api/roster','PUT',{expectedRevision:0,session:'S1',rows},manager);assert.equal((await req('/api/roster','PUT',{expectedRevision:0,session:'S1',rows},manager)).status,409);assert.equal((await req('/api/roster','PUT',{expectedRevision:1,session:'S1',rows:[rows[0],{...rows[1],studentId:'001'}]},manager)).status,400);assert.deepEqual((await req('/api/roster','GET',undefined,manager)).data.rows,rows);});
test('rotated codes and removed teachers lose access',async t=>{const {req,manager}=await fixture(t);await req('/api/roster','PUT',{expectedRevision:0,session:'S1',rows},manager);const code=(await req('/api/teacher-code','POST',{teacher:'Ms Chen'},manager)).data.code;const teacher=(await req('/api/login','POST',{role:'teacher',code})).cookie;await req('/api/teacher-code','POST',{teacher:'Ms Chen'},manager);assert.equal((await req('/api/roster','GET',undefined,teacher)).status,401);assert.equal((await req('/api/login','POST',{role:'teacher',code})).status,401);const next=(await req('/api/teacher-code','POST',{teacher:'Mr Wu'},manager)).data.code;const wu=(await req('/api/login','POST',{role:'teacher',code:next})).cookie;await req('/api/roster','PUT',{expectedRevision:1,session:'S1',rows:[rows[0]]},manager);assert.equal((await req('/api/roster','GET',undefined,wu)).status,401);});
test('roster and hashed teacher access survive restart without saving plain codes',async t=>{const {req,manager,dataDir}=await fixture(t);await req('/api/roster','PUT',{expectedRevision:0,session:'S1',rows},manager);const code=(await req('/api/teacher-code','POST',{teacher:'Ms Chen'},manager)).data.code;const raw=fs.readFileSync(path.join(dataDir,'roster-private.json'),'utf8');assert.equal(raw.includes(code),false);assert.equal(raw.includes(secret),false);const other=createExamServer({dataDir,managerCode:secret});await new Promise(resolve=>other.listen(0,'127.0.0.1',resolve));try{const base=`http://127.0.0.1:${other.address().port}`;const login=await fetch(base+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json','X-Exam-Request':'1'},body:JSON.stringify({role:'teacher',code})});assert.equal(login.status,200);const response=await fetch(base+'/api/roster',{headers:{Cookie:login.headers.get('set-cookie').split(';')[0]}});assert.equal((await response.json()).rows[0].studentId,'001');}finally{await new Promise(resolve=>other.close(resolve));}});
